# Generated by Django 5.0.4 on 2024-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=None, help_text='Add blog here'),
            preserve_default=False,
        ),
    ]
